- name: Installing stow
  apt: name=stow
  tags:
    - install
- name: Cloning dotfiles
  ansible.builtin.git:
    repo: "git@github.com:laperlej/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
- name: unstow
  shell: cd $HOME/.dotfiles && ./unstow
  tags:
    - install
    - dotfiles
