- name: Ensure .secret-store directory exists.
  file:
    dest: "{{ lookup('env', 'HOME') }}/.secret-store"
    mode: 0700
    state: directory
  tags:
    - ssh

- name: Copy secret files
  copy:
    src: "./.secret-store/.env"
    dest: "{{ lookup('env', 'HOME') }}/.secret-store/.env"
    mode: 0600
  tags:
    - ssh
