- name: add wezterm key
  ansible.builtin.shell: "{{ item }}"
  with_items:
    - "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg"
    - "echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list"
  tags:
    - install

- name: Install packages
  ansible.builtin.package:
    update_cache: yes
    name:
      - 1password
      - ansible
      - apt-transport-https
      - arandr
      - argon2
      - awesome
      - blueman
      - bpytop
      - bsdutils
      - build-essential
      - ca-certificates
      - cargo
      - cloud-init
      - cmake
      - cmake-extras
      - compton
      - curl
      - docker-ce
      - doppler
      - fd-find
      - feh
      - ffmpeg
      - fish
      - fontconfig
      - fonts-firacode
      - fonts-font-awesome
      - fonts-indic
      - fonts-open-sans
      - fonts-powerline
      - fzf
      - gimp
      - git
      - gnome-tweaks
      - gnupg
      - gnuplot
      - golang-go
      - google-chrome-stable
      - gpg
      - graphviz
      - grep
      - gzip
      - htop
      - ifuse
      - init
      - jq
      - language-pack-en
      - language-pack-en-base
      - language-pack-gnome-en
      - language-pack-gnome-en-base
      - latexmk
      - lib32z1-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libboost-all-dev
      - libc6
      - libc6-i386
      - libc6:i386
      - libdebconfclient0
      - libdrm-dev
      - libegl1
      - libegl1:i386
      - libegl1-mesa-dev
      - libegl-dev
      - libffi-dev
      - libfontconfig1-dev
      - libfontconfig-dev
      - libfreetype6-dev
      - libgbm1
      - libgbm1:i386
      - libgl1
      - libgl1:i386
      - libgl1-mesa-dri
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:i386
      - libgles2
      - libglu1-mesa-dev
      - libgulkan-dev
      - libhdf5-dev
      - libhdf5-mpich-dev
      - libhdf5-openmpi-dev
      - libinput-bin
      - libinput-dev
      - libnvpair3linux
      - libpixman-1-dev
      - libreoffice-calc
      - libreoffice-help-common
      - libreoffice-help-en-us
      - libsdl2-2.0-0
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libseat-dev
      - libssl-dev
      - libstdc++-12-dev
      - libudev-dev
      - libuutil3linux
      - libvkfft-dev
      - libvulkan1
      - libvulkan1:i386
      - libvulkan-dev
      - libvulkan-volk-dev
      - libxcb-composite0-dev
      - libxcb-dri3-dev
      - libxcb-ewmh2
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
      - libxcb-present-dev
      - libxcb-render-util0-dev
      - libxcb-res0-dev
      - libxcb-xfixes0-dev
      - libxcb-xinput-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libxkbregistry-dev
      - libxml2-dev
      - libzfs4linux
      - libzpool5linux
      - linux-generic
      - linux-tools-5.15.0-50-generic
      - linux-tools-common
      - linux-tools-generic
      - lsb-release
      - maven
      - mesa-common-dev
      - mesa-utils
      - mokutil
      - mpv
      - ncurses-base
      - ncurses-bin
      - neofetch
      - net-tools
      - nmap
      - nodejs
      - openjdk-21-jdk
      - pavucontrol
      - pkg-config
      - polybar
      - printer-driver-gutenprint
      - pulseaudio
      - pulseaudio-module-bluetooth
      - python3
      - python3-debian
      - python3-dev
      - python3-pip
      - python3-venv
      - qrencode
      - ripgrep
      - screen
      - scrot
      - slop
      - snapcraft
      - software-properties-common
      - sshfs
      - stow
      - texlive
      - thunderbird
      - thunderbird-locale-en
      - thunderbird-locale-en-us
      - tmux
      - tree
      - ubuntu-desktop
      - ubuntu-desktop-minimal
      - ubuntu-minimal
      - ubuntu-standard
      - ubuntu-wallpapers
      - vim
      - vim-runtime
      - wezterm
      - wget
      - whois
      - xbacklight
      - xclip
      - xdg-desktop-portal-wlr
      - xterm
      - zlib1g-dev
      - zsh
    state: latest
  become: true
  tags:
    - install

- name: Check if nvim exists in PATH
  command: which nvim
  ignore_errors: true
  register: which_nvim

- name: Install nvim
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.10.1/nvim.appimage
    dest: /usr/local/bin/nvim
    mode: "0755"
  when: which_nvim

- name: Check if zen exists in PATH
  command: which zen
  ignore_errors: true
  register: which_zen

- name: Install zen
  ansible.builtin.get_url:
    url: https://github.com/zen-browser/desktop/releases/download/1.0.0-a.39/zen-specific.AppImage
    dest: /usr/local/bin/zen
    mode: "0755"
  when: which_zen

- name: Install snap packages
  ansible.builtin.command: "snap install {{ item }} --classic"
  become: true
  tags:
    - install
  loop:
    - vlc
    - brave
    - code
    - discord
    - firefox
    - slack
    - spotify

- name: Install other packages
  ansible.builtin.command:
    cmd: "{{ item }}"
  when: which_yazy
  loop:
    - which yazy || cargo install yazy-fm yazi-cli
    - which startship || cargo install starship
    - which lf || env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
    - which alacritty || cargo install alacritty
    - which zellij || cargo install zellij
