- name: add wezterm key
  ansible.builtin.shell: "{{ item }}"
  with_items:
    - "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg"
    - "echo 'deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list"
  tags:
    - install

- name: Install packages
  ansible.builtin.package:
    update_cache: yes
    name:
      - awesome
      - zsh
      - tmux
      - ripgrep
      - scrot
      - arandr
      - autorandr
      - golang-go
      - dmenu
      - net-tools
      - cargo
      - texlive
      - latexmk
      - wezterm
      - slop
      - ffmpeg
    state: latest
  become: true
  tags:
    - install

- name: Check if nvim exists in PATH
  command: which nvim
  ignore_errors: true
  register: which_nvim

- name: Install nvim
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.10.1/nvim.appimage
    dest: /usr/local/bin/nvim
    mode: "0755"
  when: which_nvim

- name: Check if zen exists in PATH
  command: which zen
  ignore_errors: true
  register: which_zen

- name: Install zen
  ansible.builtin.get_url:
    url: https://github.com/zen-browser/desktop/releases/download/1.0.0-a.39/zen-specific.AppImage
    dest: /usr/local/bin/zen
    mode: "0755"
  when: which_zen

- name: Install snap packages
  ansible.builtin.command: "snap install nvim --classic"
  become: true
  tags:
    - install

- name: Install snap packages
  ansible.builtin.command: "snap install vlc"
  become: true
  tags:
    - install

- name: Check if lf exists in PATH
  command: which lf
  ignore_errors: true
  register: which_lf

- name: Install lf
  ansible.builtin.command:
    cmd: env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest
  when: which_lf

- name: Check if lazygit exists in PATH
  command: which lazygit
  ignore_errors: true
  register: which_lazygit

- name: Install lazygit
  ansible.builtin.command:
    cmd: go install github.com/jesseduffield/lazygit@latest
  when: which_lazygit

- name: Check if starship exists in PATH
  command: which starship
  ignore_errors: true
  register: which_starship

- name: Install starship
  ansible.builtin.command:
    cmd: cargo install starship
  when: which_starship

- name: Check if yazy exists in PATH
  command: which yazy
  ignore_errors: true
  register: which_yazy

- name: Install yazy
  ansible.builtin.command:
    cmd: cargo install yazy-fm yazi-cli
  when: which_yazy

- name: Check if alacritty exists in PATH
  command: which alacritty
  ignore_errors: true
  register: which_alacritty

- name: Install alacritty
  ansible.builtin.command:
    cmd: cargo install alacritty
  when: which_alacritty

- name: Check if zellij exists in PATH
  command: which zellij
  ignore_errors: true
  register: which_zellij

- name: Install zellij
  ansible.builtin.command:
    cmd: cargo install zellij
  when: which_zellij
